# Generated by Django 4.1 on 2022-08-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=15)),
                ('ponderation', models.IntegerField()),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_etudiants.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('point', models.FloatField()),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_etudiants.etudiant')),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_etudiants.cours')),
            ],
        ),
    ]
